### ISSUE TITLE
sometimes bug

### ISSUE THREAD

**Issue by VelikiySebas** [kuff/discordify#8]
![image](https://user-images.githubusercontent.com/60559667/83973745-16b88e80-a8f1-11ea-8ea9-b98339545028.png)
sometimes when run command play bot bugs like this and after this answering that im not in same voice with bot, but bot not in the voice

**Comment by kuff** [comment]
Thank you for reporting the issue!

It is not a problem I have encountered before, but from the error readout it seems to be due to a (very) slow or inconsistent internet connection.

Could you please tell me what numbers you get when running the `.ping` command?

**Comment by VelikiySebas** [comment]
![image](https://user-images.githubusercontent.com/60559667/83974507-62ba0200-a8f6-11ea-8656-026d5e757aaf.png)
oh okay, now i understand why it should be

**Comment by VelikiySebas** [comment]
now i need to have dialogue with my hosting

**Comment by kuff** [comment]
Yes, I would definitely consider your amount of latency to be the issue. Here are my numbers for comparison:

![image](https://user-images.githubusercontent.com/16867891/83974544-516cf780-a8ee-11ea-9199-1ffa59836fef.png)

If it helps, I run the bot on an AWS Lightsail instance in Virginia, Zone A. My plan is about $5 per month.

**Comment by VelikiySebas** [comment]
okay, thank you <3
